name: MAN Auto Tracker

on:
  schedule:
    - cron: "0 * * * *" # hourly
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install --omit=dev
      - name: Run MAN Tracker (auto-rotate key if due)
        run: node man.js
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Auto Tracker Bot"
          mkdir -p districttrack
          git add districttrack/
          git commit -m "Auto update: $(date '+%Y-%m-%d %H:%M')" || echo "No changes"
          git pull --rebase --autostash || echo "Pull failed"
          git push || echo "Nothing to push"
