name: Update Monthly Advance Database

on:
  schedule:
    - cron: "*/40 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pytz

      - name: Run update script
        run: python monthly_advance.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add "Monthly Advance/"
          git commit -m "Auto update Monthly Advance ($(date +'%Y-%m-%d %H:%M'))" || echo "No changes"
          git push origin main --force
